{% set version = '1.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: bioconductor-ranks
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RANKS_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RANKS/RANKS_{{ version }}.tar.gz
  sha256: 186a778ee67a37f93f11bd58a42d7269fd7c9eef7806e4996708b99e0587f3b0

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-perfmeas
    - bioconductor-graph
    - bioconductor-limma
    - bioconductor-netpreproc
    - bioconductor-rbgl
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-perfmeas
    - bioconductor-graph
    - bioconductor-limma
    - bioconductor-netpreproc
    - bioconductor-rbgl

test:
  commands:
    - $R -e "library('RANKS')"           # [not win]
    - "\"%R%\" -e \"library('RANKS')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=RANKS
  license: GPL-2.0-or-later
  summary: Implementation of Kernelized score functions and other semi-supervised learning algorithms
    for node label ranking to analyze  biomolecular networks. RANKS can be easily applied
    to a large set of different relevant problems in computational biology, ranging
    from automatic protein function prediction, to gene disease prioritization and drug
    repositioning, and more in general to any bioinformatics problem that can be formalized
    as a node label ranking problem in a graph. The modular nature of the implementation
    allows to experiment with different score functions and kernels and to easily compare
    the results with baseline network-based methods such as label propagation and random
    walk algorithms, as well as to enlarge the algorithmic scheme by adding novel user-defined
    score functions and kernels.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - leej3

# Package: RANKS
# Type: Package
# Title: Ranking of Nodes with Kernelized Score Functions
# Version: 1.1
# Date: 2022-09-20
# Authors@R: c(person("Giorgio", "Valentini", role = c("aut", "cre"), email = "valentini@di.unimi.it"))
# Author: Giorgio Valentini [aut, cre]
# Maintainer: Giorgio Valentini <valentini@di.unimi.it>
# Description: Implementation of Kernelized score functions and other semi-supervised learning algorithms for node label ranking to analyze  biomolecular networks. RANKS can be easily applied to a large set of different relevant problems in computational biology, ranging from automatic protein function prediction, to gene disease prioritization and drug repositioning, and more in general to any bioinformatics problem that can be formalized as a node label ranking problem in a graph. The modular nature of the implementation allows to experiment with different score functions and kernels and to easily compare the results with baseline network-based methods such as label propagation and random walk algorithms, as well as to enlarge the algorithmic scheme by adding novel user-defined score functions and kernels.
# License: GPL (>= 2)
# LazyLoad: yes
# Imports: methods, graph, RBGL, limma, NetPreProc, PerfMeas
# Suggests: bionetdata
# NeedsCompilation: yes
# Packaged: 2022-09-20 15:05:16 UTC; valenti
# Repository: CRAN
# Date/Publication: 2022-09-20 22:40:05 UTC
