{% set version = '1.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: bioconductor-netpreproc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/NetPreProc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/NetPreProc/NetPreProc_{{ version }}.tar.gz
  sha256: 0c998eb0d3faae4014ff13c3b4f39f140cadb18d7084103b5bba0efaf6cbb91d

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - bioconductor-graph
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - bioconductor-graph

test:
  commands:
    - $R -e "library('NetPreProc')"           # [not win]
    - "\"%R%\" -e \"library('NetPreProc')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=NetPreProc
  license: GPL-2.0-or-later
  summary: Network Pre-Processing and normalization. Methods for normalizing graphs, including
    Chua normalization, Laplacian normalization, Binary magnification, min-max normalization
    and others. Methods to sparsify adjacency matrices. Methods for graph pre-processing
    and for filtering edges of the graph.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - leej3

# Package: NetPreProc
# Type: Package
# Title: Network Pre-Processing and Normalization
# Version: 1.2
# Date: 2022-09-14
# Authors@R: c(person("Giorgio", "Valentini", role = c("aut", "cre"), email = "valentini@di.unimi.it"))
# Author: Giorgio Valentini [aut, cre]
# Maintainer: Giorgio Valentini <valentini@di.unimi.it>
# Description: Network Pre-Processing and normalization. Methods for normalizing graphs, including Chua normalization, Laplacian normalization, Binary magnification, min-max normalization and others. Methods to sparsify adjacency matrices. Methods for graph pre-processing and for filtering edges of the graph.
# License: GPL (>= 2)
# LazyLoad: yes
# Depends: methods
# Imports: graph
# Suggests: bionetdata
# NeedsCompilation: yes
# Packaged: 2022-09-16 16:36:46 UTC; valenti
# Repository: CRAN
# Date/Publication: 2022-09-19 11:06:10 UTC
