{% set version = "3.2.0" %}
{% set name = "GeomxTools" %}
{% set bioc = "3.16" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: cbfe2461c03f5e985f813a7fc41111e5
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: rmarkdown, knitr, testthat (>= 3.0.0), parallel, ggiraph
requirements:
  host:
    - 'bioconductor-biobase >=2.54.0,<2.55.0'
    - 'bioconductor-biocgenerics >=0.40.0,<0.41.0'
    - 'bioconductor-nanostringnctools >=1.2.0,<=1.4.0'
    - 'bioconductor-s4vectors >=0.32.0,<0.33.0'
    - r-base
    - r-data.table
    - r-dplyr
    - r-envstats
    - r-ggally
    - r-lmertest
    - r-outliers
    - r-readxl
    - r-reshape2
    - r-rjson
    - r-seuratobject
  run:
    - 'bioconductor-biobase >=2.54.0,<2.55.0'
    - 'bioconductor-biocgenerics >=0.40.0,<0.41.0'
    - 'bioconductor-nanostringnctools >=1.2.0,<=1.4.0'
    - 'bioconductor-s4vectors >=0.32.0,<0.33.0'
    - r-base
    - r-data.table
    - r-dplyr
    - r-envstats
    - r-ggally
    - r-lmertest
    - r-outliers
    - r-readxl
    - r-reshape2
    - r-rjson
    - r-seuratobject
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: MIT
  summary: 'NanoString GeoMx Tools'
  description: 'Tools for NanoString Technologies GeoMx Technology. Package provides functions for reading in DCC and PKC files based on an ExpressionSet derived object.  Normalization and QC functions are also included.'

