{% set version = "1.4.3" %}
{% set name = "SpatialDecon" %}
{% set bioc = "3.14" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 0249bfd07731f8ad3299be44692e768b
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - bioconductor-biobase
    - bioconductor-geomxtools
    - r-base
    - r-lognormreg
    - r-matrix
    - r-repmis
    - r-seuratobject
  run:
    - bioconductor-biobase
    - bioconductor-geomxtools
    - r-base
    - r-lognormreg
    - r-matrix
    - r-repmis
    - r-seuratobject
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL-3 + file LICENSE'
  summary: 'Deconvolution of mixed cells from spatial and/or bulk gene expression data'
  description: 'Using spatial or bulk gene expression data, estimates abundance of mixed cell types within each observation. Based on "Advances in mixed cell deconvolution enable quantification of cell types in spatially-resolved gene expression data", Danaher (2020). Designed for use with the NanoString GeoMx platform, but applicable to any gene expression data.'
  license_file: LICENSE

